name: Test Glob Pattern

on:
  push:
    branches:
      - 'rhoai-[23].[0-9]'
      - 'rhoai-[23].[0-9][0-9]'

jobs:
  print-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo "Hello from branch ${{ github.ref_name }}"
